/**
 * GlowWise demo data (development / demo use only).
 * Brand names are fictional so no real brand's prices or ratings are
 * misrepresented. Replace with real catalogue data before going live.
 *
 * Pack pricing: price = MRP (stored as priceForRetailer),
 *               discountPrice = selling price (stored as priceForWholesaler)
 */

const categories = [
  { id: 1, name: "Skincare", slug: "skincare" },
  { id: 2, name: "Makeup", slug: "makeup" },
  { id: 3, name: "Haircare", slug: "haircare" },
  { id: 4, name: "Body Care", slug: "body-care" },
  { id: 5, name: "Fragrance", slug: "fragrance" },
  { id: 6, name: "Lip Care", slug: "lip-care" },
  { id: 7, name: "Face Care", slug: "face-care" },
  { id: 8, name: "Sun Care", slug: "sun-care" },
  { id: 9, name: "Wellness", slug: "wellness" },
];

const ALL_SKIN = ["Normal", "Dry", "Oily", "Combination", "Sensitive"];

const products = [
  {
    categoryId: 1,
    productName: "Vitamin C 10% Face Serum",
    brand: "Lumière Lab",
    subcategory: "Serum",
    packs: [{ size: "30ml", price: 699, discountPrice: 599 }],
    rating: 4.6, reviewCount: 1284, stock: 120,
    skinTypes: ["Normal", "Oily", "Combination"],
    skinConcerns: ["Dullness", "Pigmentation", "Uneven Skin Tone"],
    keyIngredients: ["Vitamin C (Ethyl Ascorbic Acid)", "Hyaluronic Acid", "Ferulic Acid"],
    benefits: ["Brightens dull skin", "Helps fade dark spots", "Evens out skin tone", "Antioxidant protection"],
    howToUse: "Apply 3–4 drops on clean, dry skin in the morning. Follow with moisturizer and sunscreen.",
    description: "A lightweight, fast-absorbing vitamin C serum that brightens dull skin and helps reduce the look of pigmentation for a more even, radiant complexion.",
  },
  {
    categoryId: 1,
    productName: "Gentle Foaming Face Cleanser",
    brand: "PureDew",
    subcategory: "Cleanser",
    packs: [
      { size: "100ml", price: 399, discountPrice: 349 },
      { size: "200ml", price: 699, discountPrice: 599 },
    ],
    rating: 4.5, reviewCount: 932, stock: 200,
    skinTypes: ["Normal", "Dry", "Combination", "Sensitive"],
    skinConcerns: ["Dryness", "Sensitivity"],
    keyIngredients: ["Glycerin", "Ceramides", "Panthenol"],
    benefits: ["Cleanses without stripping moisture", "Supports the skin barrier", "Soap-free and pH balanced"],
    howToUse: "Massage a small amount onto damp face, then rinse with lukewarm water. Use morning and night.",
    description: "A soap-free, low-foam cleanser that removes dirt and impurities while keeping skin soft, hydrated and comfortable.",
  },
  {
    categoryId: 1,
    productName: "Oil-Free Gel Face Wash",
    brand: "ClearLeaf",
    subcategory: "Face Wash",
    packs: [{ size: "100ml", price: 299, discountPrice: 249 }],
    rating: 4.3, reviewCount: 2140, stock: 250,
    skinTypes: ["Oily", "Combination"],
    skinConcerns: ["Acne", "Oiliness"],
    keyIngredients: ["Salicylic Acid 1%", "Tea Tree Oil", "Zinc PCA"],
    benefits: ["Controls excess oil", "Unclogs pores", "Helps reduce breakouts"],
    howToUse: "Use twice daily on wet skin, lather gently and rinse. Avoid the eye area.",
    description: "A refreshing gel face wash with salicylic acid that deep-cleans pores and keeps oil and breakouts in check.",
  },
  {
    categoryId: 1,
    productName: "Hydrating Ceramide Moisturizer",
    brand: "Dewbloom",
    subcategory: "Moisturizer",
    packs: [{ size: "50g", price: 549, discountPrice: 469 }],
    rating: 4.7, reviewCount: 1540, stock: 140,
    skinTypes: ["Dry", "Normal", "Sensitive"],
    skinConcerns: ["Dryness", "Sensitivity", "Fine Lines"],
    keyIngredients: ["Ceramides", "Hyaluronic Acid", "Squalane"],
    benefits: ["Deep 24-hour hydration", "Repairs the moisture barrier", "Softens rough patches"],
    howToUse: "Apply a pea-sized amount to face and neck after serum, morning and night.",
    description: "A rich yet non-greasy cream that locks in moisture and strengthens the skin barrier for soft, supple skin.",
  },
  {
    categoryId: 1,
    productName: "Lightweight Oil-Free Moisturizer",
    brand: "ClearLeaf",
    subcategory: "Moisturizer",
    packs: [{ size: "50g", price: 449, discountPrice: 389 }],
    rating: 4.4, reviewCount: 876, stock: 160,
    skinTypes: ["Oily", "Combination"],
    skinConcerns: ["Oiliness", "Acne"],
    keyIngredients: ["Niacinamide", "Green Tea Extract", "Hyaluronic Acid"],
    benefits: ["Hydrates without heaviness", "Mattifying finish", "Non-comedogenic"],
    howToUse: "Apply evenly on clean skin. Ideal under sunscreen or makeup.",
    description: "A water-light gel moisturizer that hydrates oily skin while leaving a fresh, matte finish.",
  },
  {
    categoryId: 1,
    productName: "Niacinamide 10% + Zinc Serum",
    brand: "Lumière Lab",
    subcategory: "Serum",
    packs: [{ size: "30ml", price: 599, discountPrice: 499 }],
    rating: 4.5, reviewCount: 1967, stock: 180,
    skinTypes: ["Oily", "Combination", "Normal"],
    skinConcerns: ["Acne", "Oiliness", "Dark Spots", "Uneven Skin Tone"],
    keyIngredients: ["Niacinamide 10%", "Zinc PCA 1%"],
    benefits: ["Minimises the look of pores", "Balances oil", "Fades post-acne marks"],
    howToUse: "Apply a few drops morning and evening before moisturizer.",
    description: "A daily serum that refines pores, controls shine and visibly improves uneven texture.",
  },
  {
    categoryId: 8,
    productName: "SPF 50 PA++++ Sunscreen Gel",
    brand: "SunVeil",
    subcategory: "Sunscreen",
    packs: [{ size: "50g", price: 499, discountPrice: 429 }],
    rating: 4.6, reviewCount: 2310, stock: 220,
    skinTypes: ["Oily", "Combination", "Normal"],
    skinConcerns: ["Pigmentation", "Dark Spots", "Oiliness"],
    keyIngredients: ["Broad-spectrum UV filters", "Niacinamide", "Vitamin E"],
    benefits: ["High UVA/UVB protection", "No white cast", "Oil-control gel texture"],
    howToUse: "Apply generously 15 minutes before sun exposure. Reapply every 2–3 hours.",
    description: "An ultra-light, non-sticky gel sunscreen with SPF 50 PA++++ that protects without a white cast.",
  },
  {
    categoryId: 8,
    productName: "Mineral Sunscreen SPF 50 for Sensitive Skin",
    brand: "SunVeil",
    subcategory: "Sunscreen",
    packs: [{ size: "50g", price: 649, discountPrice: 559 }],
    rating: 4.4, reviewCount: 712, stock: 110,
    skinTypes: ["Sensitive", "Dry", "Normal"],
    skinConcerns: ["Sensitivity", "Pigmentation"],
    keyIngredients: ["Zinc Oxide", "Titanium Dioxide", "Centella Asiatica"],
    benefits: ["Gentle physical sun protection", "Fragrance-free", "Calms redness"],
    howToUse: "Apply as the last step of your morning routine. Reapply after sweating or swimming.",
    description: "A fragrance-free mineral sunscreen designed for sensitive skin, with soothing centella.",
  },
  {
    categoryId: 7,
    productName: "Soothing Aloe Toner",
    brand: "PureDew",
    subcategory: "Toner",
    packs: [{ size: "150ml", price: 349, discountPrice: 299 }],
    rating: 4.2, reviewCount: 540, stock: 130,
    skinTypes: ALL_SKIN,
    skinConcerns: ["Sensitivity", "Dryness"],
    keyIngredients: ["Aloe Vera", "Rose Water", "Panthenol"],
    benefits: ["Instantly refreshes", "Calms irritation", "Preps skin for serums"],
    howToUse: "After cleansing, pat onto face with palms or a cotton pad.",
    description: "An alcohol-free toner that hydrates and soothes skin, leaving it fresh and balanced.",
  },
  {
    categoryId: 7,
    productName: "Brightening Clay Face Mask",
    brand: "Dewbloom",
    subcategory: "Face Mask",
    packs: [{ size: "100g", price: 499, discountPrice: 399 }],
    rating: 4.3, reviewCount: 488, stock: 90,
    skinTypes: ["Oily", "Combination", "Normal"],
    skinConcerns: ["Dullness", "Oiliness", "Uneven Skin Tone"],
    keyIngredients: ["Kaolin Clay", "Licorice Extract", "Turmeric"],
    benefits: ["Draws out impurities", "Boosts radiance", "Smooths texture"],
    howToUse: "Apply an even layer, leave for 10 minutes and rinse. Use 2–3 times a week.",
    description: "A purifying clay mask that clears congested pores and reveals brighter-looking skin.",
  },
  {
    categoryId: 6,
    productName: "Nourishing Shea Lip Balm",
    brand: "Velvet Rose",
    subcategory: "Lip Balm",
    packs: [{ size: "4.5g", price: 199, discountPrice: 169 }],
    rating: 4.5, reviewCount: 1320, stock: 300,
    skinTypes: ALL_SKIN,
    skinConcerns: ["Dryness"],
    keyIngredients: ["Shea Butter", "Vitamin E", "Beeswax"],
    benefits: ["Heals dry, chapped lips", "Long-lasting moisture", "Subtle natural sheen"],
    howToUse: "Apply on lips as often as needed throughout the day.",
    description: "A buttery lip balm that deeply nourishes and protects dry lips.",
  },
  {
    categoryId: 2,
    productName: "Matte Liquid Lipstick",
    brand: "Velvet Rose",
    subcategory: "Lipstick",
    packs: [
      { size: "5ml – Rosewood", price: 599, discountPrice: 479 },
      { size: "5ml – Classic Red", price: 599, discountPrice: 479 },
      { size: "5ml – Nude Petal", price: 599, discountPrice: 479 },
    ],
    rating: 4.4, reviewCount: 1045, stock: 150,
    skinTypes: [],
    skinConcerns: [],
    keyIngredients: ["Vitamin E", "Jojoba Oil"],
    benefits: ["Transfer-proof matte finish", "Up to 12 hours wear", "Comfortable, non-drying"],
    howToUse: "Line lips with the applicator tip, then fill in. Let it set for 30 seconds.",
    description: "A highly pigmented liquid lipstick with a velvety matte finish that lasts all day.",
  },
  {
    categoryId: 2,
    productName: "Longwear Liquid Foundation",
    brand: "Aura Beauty",
    subcategory: "Foundation",
    packs: [
      { size: "30ml – Ivory", price: 899, discountPrice: 749 },
      { size: "30ml – Beige", price: 899, discountPrice: 749 },
      { size: "30ml – Honey", price: 899, discountPrice: 749 },
    ],
    rating: 4.3, reviewCount: 860, stock: 100,
    skinTypes: ["Normal", "Oily", "Combination"],
    skinConcerns: ["Uneven Skin Tone"],
    keyIngredients: ["Hyaluronic Acid", "SPF 15"],
    benefits: ["Medium-to-full buildable coverage", "Natural satin finish", "Sweat resistant"],
    howToUse: "Dot on face and blend outward with a sponge or brush.",
    description: "A lightweight foundation that evens skin tone with buildable coverage and a natural finish.",
  },
  {
    categoryId: 2,
    productName: "Volumizing Waterproof Mascara",
    brand: "Aura Beauty",
    subcategory: "Mascara",
    packs: [{ size: "10ml", price: 449, discountPrice: 379 }],
    rating: 4.2, reviewCount: 690, stock: 130,
    skinTypes: [],
    skinConcerns: [],
    keyIngredients: ["Castor Oil", "Panthenol"],
    benefits: ["Dramatic volume", "Smudge-proof & waterproof", "Clump-free"],
    howToUse: "Sweep from root to tip in a zig-zag motion. Remove with an oil-based remover.",
    description: "A waterproof mascara that lifts and volumizes lashes without clumping.",
  },
  {
    categoryId: 3,
    productName: "Strengthening Argan Shampoo",
    brand: "Silk & Strand",
    subcategory: "Shampoo",
    packs: [
      { size: "250ml", price: 449, discountPrice: 379 },
      { size: "500ml", price: 799, discountPrice: 649 },
    ],
    rating: 4.4, reviewCount: 1180, stock: 210,
    skinTypes: [],
    skinConcerns: ["Hair Fall", "Frizz"],
    keyIngredients: ["Argan Oil", "Keratin", "Biotin"],
    benefits: ["Reduces breakage", "Adds shine", "Sulphate-free formula"],
    howToUse: "Massage into wet hair and scalp, rinse thoroughly. Follow with conditioner.",
    description: "A sulphate-free shampoo with argan oil and keratin that strengthens hair and reduces breakage.",
  },
  {
    categoryId: 3,
    productName: "Smoothing Argan Conditioner",
    brand: "Silk & Strand",
    subcategory: "Conditioner",
    packs: [{ size: "200ml", price: 449, discountPrice: 379 }],
    rating: 4.5, reviewCount: 820, stock: 170,
    skinTypes: [],
    skinConcerns: ["Frizz", "Dryness"],
    keyIngredients: ["Argan Oil", "Shea Butter"],
    benefits: ["Detangles instantly", "Controls frizz", "Silky, soft finish"],
    howToUse: "Apply to mid-lengths and ends after shampooing, leave for 2 minutes and rinse.",
    description: "A nourishing conditioner that smooths frizz and leaves hair soft and manageable.",
  },
  {
    categoryId: 3,
    productName: "Anti-Frizz Hair Serum",
    brand: "Silk & Strand",
    subcategory: "Hair Serum",
    packs: [{ size: "100ml", price: 399, discountPrice: 329 }],
    rating: 4.3, reviewCount: 960, stock: 160,
    skinTypes: [],
    skinConcerns: ["Frizz"],
    keyIngredients: ["Argan Oil", "Vitamin E", "Silicones"],
    benefits: ["Tames flyaways", "Heat protection", "Glossy shine"],
    howToUse: "Apply 2–3 pumps to damp or dry hair, avoiding the roots.",
    description: "A lightweight serum that instantly smooths frizz and adds mirror-like shine.",
  },
  {
    categoryId: 3,
    productName: "Rosemary Hair Growth Oil",
    brand: "HerbaRoot",
    subcategory: "Hair Oil",
    packs: [{ size: "100ml", price: 349, discountPrice: 299 }],
    rating: 4.2, reviewCount: 1430, stock: 190,
    skinTypes: [],
    skinConcerns: ["Hair Fall", "Dandruff"],
    keyIngredients: ["Rosemary Oil", "Onion Seed Oil", "Coconut Oil"],
    benefits: ["Nourishes the scalp", "Helps reduce hair fall", "Strengthens roots"],
    howToUse: "Massage into the scalp, leave for at least 1 hour or overnight, then wash.",
    description: "A non-sticky herbal hair oil that nourishes the scalp and supports stronger hair.",
  },
  {
    categoryId: 4,
    productName: "Cocoa Butter Body Lotion",
    brand: "Velour Body",
    subcategory: "Body Lotion",
    packs: [{ size: "400ml", price: 499, discountPrice: 399 }],
    rating: 4.5, reviewCount: 1105, stock: 180,
    skinTypes: ["Dry", "Normal"],
    skinConcerns: ["Dryness"],
    keyIngredients: ["Cocoa Butter", "Shea Butter", "Vitamin E"],
    benefits: ["48-hour moisture", "Softens rough skin", "Fast absorbing"],
    howToUse: "Massage onto clean skin after a bath, focusing on dry areas.",
    description: "A creamy body lotion that deeply moisturizes and leaves skin soft and smooth all day.",
  },
  {
    categoryId: 4,
    productName: "Hydrating Coconut Body Wash",
    brand: "Velour Body",
    subcategory: "Body Wash",
    packs: [{ size: "250ml", price: 399, discountPrice: 329 }],
    rating: 4.3, reviewCount: 640, stock: 170,
    skinTypes: ALL_SKIN,
    skinConcerns: ["Dryness"],
    keyIngredients: ["Coconut Milk", "Glycerin", "Aloe Vera"],
    benefits: ["Gentle creamy lather", "Moisturizes while cleansing", "Light tropical fragrance"],
    howToUse: "Lather onto wet skin with a loofah and rinse well.",
    description: "A creamy body wash enriched with coconut milk that cleanses gently and keeps skin hydrated.",
  },
  {
    categoryId: 5,
    productName: "Midnight Bloom Eau de Parfum",
    brand: "Maison Éclat",
    subcategory: "Perfume",
    packs: [
      { size: "50ml", price: 1999, discountPrice: 1599 },
      { size: "100ml", price: 2999, discountPrice: 2399 },
    ],
    rating: 4.6, reviewCount: 455, stock: 80,
    skinTypes: [],
    skinConcerns: [],
    keyIngredients: ["Jasmine", "Peony", "Vanilla", "Sandalwood"],
    benefits: ["Long-lasting floral scent", "Elegant evening fragrance"],
    howToUse: "Spray on pulse points – wrists, neck and behind the ears.",
    description: "A sensual floral eau de parfum with jasmine and peony over a warm vanilla-sandalwood base.",
  },
  {
    categoryId: 5,
    productName: "Fresh Citrus Body Mist",
    brand: "Maison Éclat",
    subcategory: "Body Mist",
    packs: [{ size: "150ml", price: 599, discountPrice: 499 }],
    rating: 4.3, reviewCount: 610, stock: 140,
    skinTypes: [],
    skinConcerns: [],
    keyIngredients: ["Bergamot", "Orange Blossom", "Aloe Vera"],
    benefits: ["Light, refreshing everyday scent", "Alcohol-light formula"],
    howToUse: "Mist all over the body after a shower or whenever you need a refresh.",
    description: "A bright, uplifting body mist with sparkling citrus and soft orange blossom.",
  },
  {
    categoryId: 9,
    productName: "Biotin & Vitamin C Beauty Gummies",
    brand: "GlowVita",
    subcategory: "Supplements",
    packs: [{ size: "30 gummies", price: 799, discountPrice: 649 }],
    rating: 4.1, reviewCount: 380, stock: 120,
    skinTypes: [],
    skinConcerns: ["Hair Fall", "Dullness"],
    keyIngredients: ["Biotin", "Vitamin C", "Zinc"],
    benefits: ["Supports healthy hair, skin and nails", "Tasty berry flavour"],
    howToUse: "Chew 1 gummy daily after a meal. Do not exceed the recommended dose. Consult a doctor if pregnant or on medication.",
    description: "Delicious berry-flavoured gummies with biotin, vitamin C and zinc to complement your beauty routine. A food supplement, not a medicine.",
  },
];

module.exports = { categories, products };
